### ISSUE TITLE
VenueExists doesn't exist?

### ISSUE THREAD

**Issue by generalredneck** [OpenKJ/StandaloneRequestServer#1]
I can't seem to find the venueExists function anywhere. I'm pretty sure that in this verison, it should return TRUE if the `$venueUrlName == 'none'`. I say that... but I suspect the app doesn't know which venues are available because if I recall, the phone app is a type in box for this... OpenKJ doesn't seem to call this function.

https://github.com/OpenKJ/StandaloneRequestServer/blob/3fc24151e66c3c54ee36fbc0c5282acaf10e8b07/api.php#L17

**Comment by ILightburn** [comment]
That's just something that got left in when I pared down the code from the full code used on songbook.openkj.org. The Android/iOS apps call it when validating the venueid that a user enters.  It won't matter until I modify the apps to work with the standalone server.
