### ISSUE TITLE
GetAccepting command doesn't look coorect

### ISSUE THREAD

**Issue by generalredneck** [OpenKJ/StandaloneRequestServer#2]
So looking at the GetAccepting command, it appears that you aren't sending back the correct information. I don't see where you are setting the $venue variable or using the $accepting variable. 
https://github.com/OpenKJ/StandaloneRequestServer/blob/8449490/api.php#L182-L189

**Comment by ILightburn** [comment]
Yep, I screwed that one up.  I think I was half asleep when I was adapting the main site code.  Btw, OpenKJ doesn't actually call that API call.  It just reads it from the venue info.  That's why I didn't notice that it was broken in testing.
